jwt:
  secret: taemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemin
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: taemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemintaemin
    tokenExpiry: 30000000000000
  oauth2:
    authorizedRedirectUris: http://localhost:3000/oauth2/redirect